//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PenStore.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id_order { get; set; }
        public Nullable<System.DateTime> DataOrder { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Id_pen { get; set; }
        public Nullable<int> Id_client { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Pen Pen { get; set; }
    }
}
