//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PenStore.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypePen
    {
        public TypePen()
        {
            this.Pen = new HashSet<Pen>();
        }
    
        public int Id_typePen { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Pen> Pen { get; set; }
    }
}
